services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - models:/root/.cache/whisper
      - db:/app/db

volumes:
  models:
  db: