services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - models:/root/.cache/whisper
      - db:/app/db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  models:
  db: