services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 10000:10000
    volumes:
      - models:/root/.cache/whisper
      - db:/app/db
      - ./server/.env:/app/.env

volumes:
  models:
  db: